-- Create recipes table
create table public.recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  ingredients jsonb,
  instructions jsonb,
  source_url text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create pantry_items table
create table public.pantry_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  is_low_stock boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create shopping_list table
create table public.shopping_list (
  id bigint generated by default as identity primary key,
  name text not null,
  bought boolean default false,
  recipe_id bigint references public.recipes(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create planned_recipes table
create table public.planned_recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  source_url text,
  image_url text,
  planned_at timestamp with time zone,
  "order" integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.recipes enable row level security;
alter table public.pantry_items enable row level security;
alter table public.shopping_list enable row level security;
alter table public.planned_recipes enable row level security;

-- Create policies to allow anonymous access (for development/demo purposes)
create policy "Enable read access for all users" on public.recipes for select using (true);
create policy "Enable insert access for all users" on public.recipes for insert with check (true);
create policy "Enable update access for all users" on public.recipes for update using (true);
create policy "Enable delete access for all users" on public.recipes for delete using (true);

create policy "Enable read access for all users" on public.pantry_items for select using (true);
create policy "Enable insert access for all users" on public.pantry_items for insert with check (true);
create policy "Enable update access for all users" on public.pantry_items for update using (true);
create policy "Enable delete access for all users" on public.pantry_items for delete using (true);

create policy "Enable read access for all users" on public.shopping_list for select using (true);
create policy "Enable insert access for all users" on public.shopping_list for insert with check (true);
create policy "Enable update access for all users" on public.shopping_list for update using (true);
create policy "Enable delete access for all users" on public.shopping_list for delete using (true);

create policy "Enable read access for all users" on public.planned_recipes for select using (true);
create policy "Enable insert access for all users" on public.planned_recipes for insert with check (true);
create policy "Enable update access for all users" on public.planned_recipes for update using (true);
create policy "Enable delete access for all users" on public.planned_recipes for delete using (true);
